// Code generated by protoc-gen-go. DO NOT EDIT.
// source: anime_proto.proto

package com_egoist_mal_grpc_generated

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AnimeSearchRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnimeSearchRequest) Reset()         { *m = AnimeSearchRequest{} }
func (m *AnimeSearchRequest) String() string { return proto.CompactTextString(m) }
func (*AnimeSearchRequest) ProtoMessage()    {}
func (*AnimeSearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c072c1d3fd4052a, []int{0}
}

func (m *AnimeSearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnimeSearchRequest.Unmarshal(m, b)
}
func (m *AnimeSearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnimeSearchRequest.Marshal(b, m, deterministic)
}
func (m *AnimeSearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnimeSearchRequest.Merge(m, src)
}
func (m *AnimeSearchRequest) XXX_Size() int {
	return xxx_messageInfo_AnimeSearchRequest.Size(m)
}
func (m *AnimeSearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AnimeSearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AnimeSearchRequest proto.InternalMessageInfo

func (m *AnimeSearchRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AnimeSearchRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type AnimeSearchResponse struct {
	Status               int32        `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string       `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 []*AnimeData `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AnimeSearchResponse) Reset()         { *m = AnimeSearchResponse{} }
func (m *AnimeSearchResponse) String() string { return proto.CompactTextString(m) }
func (*AnimeSearchResponse) ProtoMessage()    {}
func (*AnimeSearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c072c1d3fd4052a, []int{1}
}

func (m *AnimeSearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnimeSearchResponse.Unmarshal(m, b)
}
func (m *AnimeSearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnimeSearchResponse.Marshal(b, m, deterministic)
}
func (m *AnimeSearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnimeSearchResponse.Merge(m, src)
}
func (m *AnimeSearchResponse) XXX_Size() int {
	return xxx_messageInfo_AnimeSearchResponse.Size(m)
}
func (m *AnimeSearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AnimeSearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AnimeSearchResponse proto.InternalMessageInfo

func (m *AnimeSearchResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *AnimeSearchResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *AnimeSearchResponse) GetData() []*AnimeData {
	if m != nil {
		return m.Data
	}
	return nil
}

type AnimeData struct {
	AnimeId              int32    `protobuf:"varint,1,opt,name=anime_id,json=animeId,proto3" json:"anime_id,omitempty"`
	EnName               string   `protobuf:"bytes,2,opt,name=en_name,json=enName,proto3" json:"en_name,omitempty"`
	JpName               string   `protobuf:"bytes,3,opt,name=jp_name,json=jpName,proto3" json:"jp_name,omitempty"`
	Pic                  string   `protobuf:"bytes,4,opt,name=pic,proto3" json:"pic,omitempty"`
	AnimeType            string   `protobuf:"bytes,5,opt,name=anime_type,json=animeType,proto3" json:"anime_type,omitempty"`
	Episodes             int32    `protobuf:"varint,6,opt,name=episodes,proto3" json:"episodes,omitempty"`
	Premiered            string   `protobuf:"bytes,7,opt,name=premiered,proto3" json:"premiered,omitempty"`
	Producers            string   `protobuf:"bytes,8,opt,name=producers,proto3" json:"producers,omitempty"`
	Studios              string   `protobuf:"bytes,9,opt,name=studios,proto3" json:"studios,omitempty"`
	Source               string   `protobuf:"bytes,10,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnimeData) Reset()         { *m = AnimeData{} }
func (m *AnimeData) String() string { return proto.CompactTextString(m) }
func (*AnimeData) ProtoMessage()    {}
func (*AnimeData) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c072c1d3fd4052a, []int{2}
}

func (m *AnimeData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnimeData.Unmarshal(m, b)
}
func (m *AnimeData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnimeData.Marshal(b, m, deterministic)
}
func (m *AnimeData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnimeData.Merge(m, src)
}
func (m *AnimeData) XXX_Size() int {
	return xxx_messageInfo_AnimeData.Size(m)
}
func (m *AnimeData) XXX_DiscardUnknown() {
	xxx_messageInfo_AnimeData.DiscardUnknown(m)
}

var xxx_messageInfo_AnimeData proto.InternalMessageInfo

func (m *AnimeData) GetAnimeId() int32 {
	if m != nil {
		return m.AnimeId
	}
	return 0
}

func (m *AnimeData) GetEnName() string {
	if m != nil {
		return m.EnName
	}
	return ""
}

func (m *AnimeData) GetJpName() string {
	if m != nil {
		return m.JpName
	}
	return ""
}

func (m *AnimeData) GetPic() string {
	if m != nil {
		return m.Pic
	}
	return ""
}

func (m *AnimeData) GetAnimeType() string {
	if m != nil {
		return m.AnimeType
	}
	return ""
}

func (m *AnimeData) GetEpisodes() int32 {
	if m != nil {
		return m.Episodes
	}
	return 0
}

func (m *AnimeData) GetPremiered() string {
	if m != nil {
		return m.Premiered
	}
	return ""
}

func (m *AnimeData) GetProducers() string {
	if m != nil {
		return m.Producers
	}
	return ""
}

func (m *AnimeData) GetStudios() string {
	if m != nil {
		return m.Studios
	}
	return ""
}

func (m *AnimeData) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func init() {
	proto.RegisterType((*AnimeSearchRequest)(nil), "com.egoist.mal.grpc.generated.AnimeSearchRequest")
	proto.RegisterType((*AnimeSearchResponse)(nil), "com.egoist.mal.grpc.generated.AnimeSearchResponse")
	proto.RegisterType((*AnimeData)(nil), "com.egoist.mal.grpc.generated.AnimeData")
}

func init() { proto.RegisterFile("anime_proto.proto", fileDescriptor_9c072c1d3fd4052a) }

var fileDescriptor_9c072c1d3fd4052a = []byte{
	// 364 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x3d, 0xaf, 0xda, 0x30,
	0x14, 0x2d, 0x04, 0x12, 0x72, 0xbb, 0x80, 0x2b, 0x15, 0x17, 0x15, 0x09, 0x65, 0x62, 0x8a, 0x54,
	0xba, 0xb2, 0x54, 0xea, 0xd2, 0xa5, 0xaa, 0x42, 0x77, 0xe4, 0xda, 0x57, 0xa9, 0x51, 0x13, 0x1b,
	0xdb, 0xa9, 0xca, 0xd0, 0xf5, 0xfd, 0x81, 0xf7, 0x87, 0x9f, 0x72, 0x1d, 0x90, 0x58, 0x9e, 0xde,
	0x5b, 0xac, 0x7b, 0xce, 0xd1, 0xb9, 0x5f, 0xbe, 0xb0, 0x10, 0xad, 0x6e, 0xf0, 0x68, 0x9d, 0x09,
	0xa6, 0xa4, 0x97, 0xad, 0xa5, 0x69, 0x4a, 0xac, 0x8d, 0xf6, 0xa1, 0x6c, 0xc4, 0x9f, 0xb2, 0x76,
	0x56, 0x96, 0x35, 0xb6, 0xe8, 0x44, 0x40, 0x55, 0xec, 0x81, 0x7d, 0xe9, 0x3d, 0x07, 0x14, 0x4e,
	0xfe, 0xae, 0xf0, 0xdc, 0xa1, 0x0f, 0x8c, 0xc1, 0xa4, 0x15, 0x0d, 0xf2, 0xd1, 0x66, 0xb4, 0xcd,
	0x2b, 0x8a, 0x7b, 0x2e, 0xe0, 0xbf, 0xc0, 0xc7, 0x91, 0xeb, 0xe3, 0xe2, 0x3f, 0xbc, 0xbb, 0x73,
	0x7b, 0x6b, 0x5a, 0x8f, 0xec, 0x3d, 0xa4, 0x3e, 0x88, 0xd0, 0x79, 0x4a, 0x30, 0xad, 0x06, 0xc4,
	0xe6, 0x90, 0x34, 0xbe, 0x1e, 0x32, 0xf4, 0x21, 0xdb, 0xc3, 0x44, 0x89, 0x20, 0x78, 0xb2, 0x49,
	0xb6, 0x6f, 0x77, 0xdb, 0xf2, 0xd9, 0x66, 0x4b, 0xaa, 0xf5, 0x55, 0x04, 0x51, 0x91, 0xab, 0x78,
	0x1c, 0x43, 0x7e, 0xe3, 0xd8, 0x07, 0x98, 0xc5, 0xf1, 0xb5, 0x1a, 0xea, 0x66, 0x84, 0xbf, 0x29,
	0xb6, 0x84, 0x0c, 0xdb, 0x23, 0x8d, 0x14, 0x8b, 0xa7, 0xd8, 0x7e, 0xef, 0x87, 0x5a, 0x42, 0x76,
	0xb2, 0x51, 0x48, 0xa2, 0x70, 0xb2, 0x24, 0xcc, 0x21, 0xb1, 0x5a, 0xf2, 0x49, 0x6c, 0xd5, 0x6a,
	0xc9, 0xd6, 0x00, 0x31, 0x7d, 0xb8, 0x58, 0xe4, 0x53, 0x12, 0x72, 0x62, 0x7e, 0x5e, 0x2c, 0xb2,
	0x15, 0xcc, 0xd0, 0x6a, 0x6f, 0x14, 0x7a, 0x9e, 0x52, 0xf5, 0x1b, 0x66, 0x1f, 0x21, 0xb7, 0x0e,
	0x1b, 0x8d, 0x0e, 0x15, 0xcf, 0xa2, 0xf3, 0x46, 0x44, 0xd5, 0xa8, 0x4e, 0xa2, 0xf3, 0x7c, 0x76,
	0x55, 0x07, 0x82, 0x71, 0xc8, 0x7c, 0xe8, 0x94, 0x36, 0x9e, 0xe7, 0xa4, 0x5d, 0x21, 0x6d, 0xd9,
	0x74, 0x4e, 0x22, 0x87, 0xd8, 0x7a, 0x44, 0xbb, 0x87, 0x11, 0x2c, 0x68, 0x2b, 0x3f, 0xfa, 0x03,
	0x38, 0xa0, 0xfb, 0xab, 0x25, 0xb2, 0x33, 0xa4, 0x9e, 0x7e, 0x89, 0x7d, 0x7a, 0xc9, 0x96, 0xef,
	0xee, 0x61, 0xb5, 0x7b, 0x8d, 0x25, 0x1e, 0x41, 0xf1, 0xe6, 0x57, 0x4a, 0x17, 0xf8, 0xf9, 0x29,
	0x00, 0x00, 0xff, 0xff, 0x58, 0xac, 0x88, 0x65, 0x96, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AnimeProtoServiceClient is the client API for AnimeProtoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AnimeProtoServiceClient interface {
	Search(ctx context.Context, in *AnimeSearchRequest, opts ...grpc.CallOption) (*AnimeSearchResponse, error)
}

type animeProtoServiceClient struct {
	cc *grpc.ClientConn
}

func NewAnimeProtoServiceClient(cc *grpc.ClientConn) AnimeProtoServiceClient {
	return &animeProtoServiceClient{cc}
}

func (c *animeProtoServiceClient) Search(ctx context.Context, in *AnimeSearchRequest, opts ...grpc.CallOption) (*AnimeSearchResponse, error) {
	out := new(AnimeSearchResponse)
	err := c.cc.Invoke(ctx, "/com.egoist.mal.grpc.generated.AnimeProtoService/search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnimeProtoServiceServer is the server API for AnimeProtoService service.
type AnimeProtoServiceServer interface {
	Search(context.Context, *AnimeSearchRequest) (*AnimeSearchResponse, error)
}

// UnimplementedAnimeProtoServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAnimeProtoServiceServer struct {
}

func (*UnimplementedAnimeProtoServiceServer) Search(ctx context.Context, req *AnimeSearchRequest) (*AnimeSearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}

func RegisterAnimeProtoServiceServer(s *grpc.Server, srv AnimeProtoServiceServer) {
	s.RegisterService(&_AnimeProtoService_serviceDesc, srv)
}

func _AnimeProtoService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnimeSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnimeProtoServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.egoist.mal.grpc.generated.AnimeProtoService/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnimeProtoServiceServer).Search(ctx, req.(*AnimeSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AnimeProtoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.egoist.mal.grpc.generated.AnimeProtoService",
	HandlerType: (*AnimeProtoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "search",
			Handler:    _AnimeProtoService_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "anime_proto.proto",
}
